// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use gst_controller_sys;

glib_wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct ControlPoint(Boxed<gst_controller_sys::GstControlPoint>);

    match fn {
        copy => |ptr| gst_controller_sys::gst_control_point_copy(mut_override(ptr)),
        free => |ptr| gst_controller_sys::gst_control_point_free(ptr),
        get_type => || gst_controller_sys::gst_control_point_get_type(),
    }
}

unsafe impl Send for ControlPoint {}
unsafe impl Sync for ControlPoint {}
